<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>QTranslate-Setup</AssemblyName>
    <RootNamespace>QTranslateFix</RootNamespace>
    <Product>QTranslate 安裝程式</Product>
    <AssemblyTitle>QTranslate 安裝程式</AssemblyTitle>
    <Version>6.10.1</Version>
    <InvariantGlobalization>true</InvariantGlobalization>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <DebugType>none</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\QTranslate.zip" LogicalName="QTranslate.zip" />
    <EmbeddedResource Include="Resources\Options.default.json" LogicalName="Options.default.json" />
  </ItemGroup>

</Project>
